# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Langston Johnson
email: langstoncjohnson@gmail.com
linkedin: https://www.linkedin.com/in/langston-johnson/
github: https://github.com/Langgit72/
crt: https://cornellrocketryteam.com/

description: Engineering Portfolio and Blog of Langston C. Johnson
  # This description will show up in your feed, and in the meta description tag
  # of your site's pages. It will also show up in search results.
baseurl: "/langisblog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:year/:month/:day/:title:output_ext
#twitter_username: jekyllrb
github_username:  Langgit72

projects:
  mechanical:
    name: "Mechanical and Aerospace Engineering"
    description: "Solidworks. Ansys. MATLAB. Systems Engineering."
    items:
      project1:
        name: "Cornell Rocketry - Airbrakes [Ongoing]"
        description: "System Modeling, Requirements, and Mechanical Design of Airbrakes for Apogee Control."
        link: '/projects/project_airbrakes'
      project2:
        name: "Cornell Rocketry - Boat Tail and PCB Mounts"
        description: "System Integration and Testing of a 1U CubeSat that deployed the worlds first free-flying light sail"
        link: "{{'_projects/PCB Mounts.html'|relative_url}}"

  software:
    name: "Software Engineering"
    description: "Git. Embedded Systems. C#. Python. JavaScript. HTML/CSS. Unity Game Engine"
    items:
      project1:
          name: "High Altitude Balloon Flight Software"
          description: "Embedded Software for a High Altitude Balloon Payload"
          link: "{{'_projects/project_hab_software.html'|relative_url}}"
      project2:
          name: "Free Drift"
          description: "Pixel Art Space Exploration Written in C#. Developed in the Unity Game Engine"
          link: "{{'_projects/project_free_drift.html'|relative_url}}"
        
#favicon:
 # source: favicon.svg
# Build settings
theme: minima
plugins:
  - jekyll-feed



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
